apiVersion: v1                                                                              
kind: PersistentVolumeClaim                                                                 
metadata:                                                                                   
  name: csi-pvc-opensdsplugin                                                               
spec:                                                                                       
  accessModes:                                                                              
  - ReadWriteOnce                                                                           
  resources:                                                                                
    requests:                                                                               
      storage: 1Gi                                                                          
  storageClassName: csi-sc-opensdsplugin                                                    
root@k8s-master:/opt/opensds-k8s/csi/test# cat provice-pv-for-single-pod/nginx.yaml         
apiVersion: v1                                                                              
kind: Pod                                                                                   
metadata:                                                                                   
  name: nginx                                                                               
spec:                                                                                       
  containers:                                                                               
  - image: nginx                                                                            
    imagePullPolicy: IfNotPresent                                                           
    name: nginx                                                                             
    ports:                                                                                  
    - containerPort: 80                                                                     
      protocol: TCP                                                                         
    volumeMounts:                                                                           
      - mountPath: /var/lib/www/html                                                        
        name: csi-data-opensdsplugin                                                        
  volumes:                                                                                  
  - name: csi-data-opensdsplugin                                                            
    persistentVolumeClaim:                                                                  
      claimName: csi-pvc-opensdsplugin                                                      
      readOnly: false                                                                       
